package main

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// ReportConfig is the YAML structure generated by the operator and read by this binary.
type ReportConfig struct {
	Endpoints []EndpointConfig `yaml:"endpoints"`
}

// EndpointConfig defines a single report forwarding endpoint.
type EndpointConfig struct {
	Name           string         `yaml:"name"`
	Processor      string         `yaml:"processor"` // "puppetdb" or ""
	URL            string         `yaml:"url"`
	TimeoutSeconds int            `yaml:"timeoutSeconds"`
	Auth           AuthConfig     `yaml:"auth"`
	SSL            SSLConfig      `yaml:"ssl"`
	Headers        []HeaderConfig `yaml:"headers"`
}

// AuthConfig defines authentication settings.
type AuthConfig struct {
	Type     string `yaml:"type"`     // mtls, token, bearer, basic, or empty
	Header   string `yaml:"header"`   // custom header name (token auth)
	Token    string `yaml:"token"`    // token value (token or bearer auth)
	Username string `yaml:"username"` // basic auth username
	Password string `yaml:"password"` // basic auth password
}

// SSLConfig defines SSL/TLS settings for mTLS.
type SSLConfig struct {
	CertFile string `yaml:"certFile"`
	KeyFile  string `yaml:"keyFile"`
	CAFile   string `yaml:"caFile"`
}

// HeaderConfig defines a custom HTTP header.
type HeaderConfig struct {
	Name  string `yaml:"name"`
	Value string `yaml:"value"`
}

// loadReportConfig reads and parses the report config YAML file.
func loadReportConfig(path string) (*ReportConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading report config: %w", err)
	}
	var cfg ReportConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing report config: %w", err)
	}
	// Set defaults
	for i := range cfg.Endpoints {
		if cfg.Endpoints[i].TimeoutSeconds == 0 {
			cfg.Endpoints[i].TimeoutSeconds = 30
		}
	}
	return &cfg, nil
}

// forward sends the report to the specified endpoint.
func forward(endpoint EndpointConfig, reportJSON []byte) error {
	var body []byte
	var err error
	url := endpoint.URL

	// Transform report based on processor type
	switch endpoint.Processor {
	case "puppetdb":
		body, err = transformToPuppetDB(reportJSON)
		if err != nil {
			return fmt.Errorf("transforming to PuppetDB format: %w", err)
		}
		// PuppetDB command endpoint
		url = strings.TrimRight(endpoint.URL, "/") + "/pdb/cmd/v1"
	default:
		// Generic: forward as-is
		body = reportJSON
	}

	req, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	// Set auth header
	switch endpoint.Auth.Type {
	case "token":
		req.Header.Set(endpoint.Auth.Header, endpoint.Auth.Token)
	case "bearer":
		req.Header.Set("Authorization", "Bearer "+endpoint.Auth.Token)
	case "basic":
		req.SetBasicAuth(endpoint.Auth.Username, endpoint.Auth.Password)
	}

	// Set custom headers
	for _, h := range endpoint.Headers {
		req.Header.Set(h.Name, h.Value)
	}

	client, err := buildHTTPClient(endpoint)
	if err != nil {
		return fmt.Errorf("building HTTP client: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("HTTP request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 10*1024*1024))
	if err != nil {
		return fmt.Errorf("reading response: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
	}

	return nil
}

// buildHTTPClient creates an http.Client with TLS and timeout configuration.
func buildHTTPClient(endpoint EndpointConfig) (*http.Client, error) {
	tlsConfig := &tls.Config{MinVersion: tls.VersionTLS12}

	// Load CA certificate for server verification
	if endpoint.SSL.CAFile != "" {
		caCert, err := os.ReadFile(endpoint.SSL.CAFile)
		if err != nil {
			return nil, fmt.Errorf("reading CA cert: %w", err)
		}
		caCertPool := x509.NewCertPool()
		if !caCertPool.AppendCertsFromPEM(caCert) {
			return nil, fmt.Errorf("failed to parse CA certificate")
		}
		tlsConfig.RootCAs = caCertPool
	}

	// mTLS: load client certificate
	if endpoint.Auth.Type == "mtls" && endpoint.SSL.CertFile != "" && endpoint.SSL.KeyFile != "" {
		cert, err := tls.LoadX509KeyPair(endpoint.SSL.CertFile, endpoint.SSL.KeyFile)
		if err != nil {
			return nil, fmt.Errorf("loading client certificate: %w", err)
		}
		tlsConfig.Certificates = []tls.Certificate{cert}
	}

	return &http.Client{
		Timeout: time.Duration(endpoint.TimeoutSeconds) * time.Second,
		Transport: &http.Transport{
			TLSClientConfig: tlsConfig,
		},
	}, nil
}
