package main

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

var validCertname = regexp.MustCompile(`^[a-zA-Z0-9._-]+$`)

// validateCertname returns an error if certname contains characters that could
// be used for path traversal or URL injection.
func validateCertname(certname string) error {
	if !validCertname.MatchString(certname) {
		return fmt.Errorf("invalid certname %q: must match [a-zA-Z0-9._-]+", certname)
	}
	return nil
}

// ENCConfig is the YAML structure generated by the operator and read by this binary.
type ENCConfig struct {
	URL            string      `yaml:"url"`
	Method         string      `yaml:"method"`
	Path           string      `yaml:"path"`
	Body           string      `yaml:"body"`
	ResponseFormat string      `yaml:"responseFormat"`
	TimeoutSeconds int         `yaml:"timeoutSeconds"`
	Auth           AuthConfig  `yaml:"auth"`
	Cache          CacheConfig `yaml:"cache"`
	SSL            SSLConfig   `yaml:"ssl"`
}

// AuthConfig defines authentication settings.
type AuthConfig struct {
	Type     string `yaml:"type"`     // mtls, token, bearer, basic, or empty
	Header   string `yaml:"header"`   // custom header name (token auth)
	Token    string `yaml:"token"`    // token value (token or bearer auth)
	Username string `yaml:"username"` // basic auth username
	Password string `yaml:"password"` // basic auth password
}

// CacheConfig defines cache settings.
type CacheConfig struct {
	Enabled   bool   `yaml:"enabled"`
	Directory string `yaml:"directory"`
}

// SSLConfig defines SSL/TLS settings for mTLS.
type SSLConfig struct {
	CertFile string `yaml:"certFile"`
	KeyFile  string `yaml:"keyFile"`
	CAFile   string `yaml:"caFile"`
}

// ENCResult represents a Puppet ENC response.
type ENCResult struct {
	Classes     interface{}            `yaml:"classes" json:"classes"`
	Parameters  map[string]interface{} `yaml:"parameters,omitempty" json:"parameters,omitempty"`
	Environment string                 `yaml:"environment,omitempty" json:"environment,omitempty"`
}

// notFoundError indicates a 404 response.
type notFoundError struct{ msg string }

func (e *notFoundError) Error() string { return e.msg }

func isNotFound(err error) bool {
	_, ok := err.(*notFoundError)
	return ok
}

// loadENCConfig reads and parses the ENC config YAML file.
func loadENCConfig(path string) (*ENCConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading ENC config: %w", err)
	}
	var cfg ENCConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing ENC config: %w", err)
	}
	if cfg.TimeoutSeconds == 0 {
		cfg.TimeoutSeconds = 10
	}
	if cfg.Method == "" {
		cfg.Method = "GET"
	}
	if cfg.ResponseFormat == "" {
		cfg.ResponseFormat = "yaml"
	}
	return &cfg, nil
}

// classify queries the external classifier and returns Puppet ENC YAML.
func classify(cfg *ENCConfig, certname string) (string, error) {
	if err := validateCertname(certname); err != nil {
		return "", err
	}

	reqURL := cfg.URL + strings.ReplaceAll(cfg.Path, "{certname}", url.PathEscape(certname))

	var bodyReader io.Reader
	if cfg.Method == "POST" && cfg.Body != "" {
		bodyData, err := buildRequestBody(cfg.Body, certname)
		if err != nil {
			return "", fmt.Errorf("building request body: %w", err)
		}
		bodyReader = strings.NewReader(bodyData)
	}

	req, err := http.NewRequest(cfg.Method, reqURL, bodyReader)
	if err != nil {
		return "", fmt.Errorf("creating request: %w", err)
	}

	if cfg.Method == "POST" && cfg.Body != "" {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json, application/yaml, text/yaml")

	// Set auth header
	switch cfg.Auth.Type {
	case "token":
		req.Header.Set(cfg.Auth.Header, cfg.Auth.Token)
	case "bearer":
		req.Header.Set("Authorization", "Bearer "+cfg.Auth.Token)
	case "basic":
		req.SetBasicAuth(cfg.Auth.Username, cfg.Auth.Password)
	}

	client, err := buildHTTPClient(cfg)
	if err != nil {
		return "", fmt.Errorf("building HTTP client: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("HTTP request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading response: %w", err)
	}

	if resp.StatusCode == http.StatusNotFound {
		return "", &notFoundError{msg: fmt.Sprintf("HTTP 404: %s", reqURL)}
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
	}

	return normalizeResponse(respBody, cfg.ResponseFormat)
}

// buildRequestBody creates the POST body based on body type.
func buildRequestBody(bodyType, certname string) (string, error) {
	switch bodyType {
	case "certname":
		data, err := json.Marshal(map[string]string{"certname": certname})
		return string(data), err
	case "facts":
		facts := loadFacts(certname)
		data, err := json.Marshal(map[string]interface{}{
			"certname": certname,
			"facts":    facts,
		})
		return string(data), err
	default:
		return "", nil
	}
}

// loadFacts reads Puppet facts for a certname from the YAML facts cache.
func loadFacts(certname string) map[string]interface{} {
	safeName := filepath.Base(certname)
	factsPath := filepath.Join("/opt/puppetlabs/server/data/puppetserver/yaml/facts", safeName+".yaml")
	data, err := os.ReadFile(factsPath)
	if err != nil {
		return map[string]interface{}{}
	}

	var factsFile struct {
		Values map[string]interface{} `yaml:"values"`
	}
	if err := yaml.Unmarshal(data, &factsFile); err != nil {
		return map[string]interface{}{}
	}
	if factsFile.Values == nil {
		return map[string]interface{}{}
	}
	return factsFile.Values
}

// normalizeResponse parses the classifier response and outputs Puppet ENC YAML.
func normalizeResponse(body []byte, format string) (string, error) {
	var result ENCResult

	switch format {
	case "json":
		if err := json.Unmarshal(body, &result); err != nil {
			return "", fmt.Errorf("parsing JSON response: %w", err)
		}
	case "yaml":
		if err := yaml.Unmarshal(body, &result); err != nil {
			return "", fmt.Errorf("parsing YAML response: %w", err)
		}
	default:
		return "", fmt.Errorf("unsupported response format: %s", format)
	}

	// Ensure classes is never nil
	if result.Classes == nil {
		result.Classes = map[string]interface{}{}
	}

	out, err := yaml.Marshal(&result)
	if err != nil {
		return "", fmt.Errorf("marshalling ENC result: %w", err)
	}
	return string(out), nil
}

// buildHTTPClient creates an http.Client with TLS and timeout configuration.
func buildHTTPClient(cfg *ENCConfig) (*http.Client, error) {
	tlsConfig := &tls.Config{MinVersion: tls.VersionTLS12}

	// Load CA certificate for server verification
	if cfg.SSL.CAFile != "" {
		caCert, err := os.ReadFile(cfg.SSL.CAFile)
		if err != nil {
			return nil, fmt.Errorf("reading CA cert: %w", err)
		}
		caCertPool := x509.NewCertPool()
		if !caCertPool.AppendCertsFromPEM(caCert) {
			return nil, fmt.Errorf("failed to parse CA certificate")
		}
		tlsConfig.RootCAs = caCertPool
	}

	// mTLS: load client certificate
	if cfg.Auth.Type == "mtls" && cfg.SSL.CertFile != "" && cfg.SSL.KeyFile != "" {
		cert, err := tls.LoadX509KeyPair(cfg.SSL.CertFile, cfg.SSL.KeyFile)
		if err != nil {
			return nil, fmt.Errorf("loading client certificate: %w", err)
		}
		tlsConfig.Certificates = []tls.Certificate{cert}
	}

	return &http.Client{
		Timeout: time.Duration(cfg.TimeoutSeconds) * time.Second,
		Transport: &http.Transport{
			TLSClientConfig: tlsConfig,
		},
	}, nil
}

// saveCache writes the classification result to a cache file.
func saveCache(dir, certname, data string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	safeName := filepath.Base(certname)
	path := filepath.Join(dir, safeName+".yaml")
	return os.WriteFile(path, []byte(data), 0644)
}

// readCache reads a cached classification result.
func readCache(dir, certname string) (string, error) {
	safeName := filepath.Base(certname)
	path := filepath.Join(dir, safeName+".yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}
