apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Config
metadata:
  name: {{ include "openvox-stack.configName" . }}
spec:
  authorityRef: {{ include "openvox-stack.caName" . }}
  {{- if .Values.nodeClassifier.enabled }}
  nodeClassifierRef: {{ include "openvox-stack.nodeClassifierName" . }}
  {{- end }}
  image:
    repository: {{ .Values.config.image.repository }}
    tag: {{ .Values.config.image.tag | quote }}
    pullPolicy: {{ .Values.config.image.pullPolicy }}
  {{- with .Values.config.puppetdb }}
  {{- if .serverUrls }}
  puppetdb:
    serverUrls:
      {{- toYaml .serverUrls | nindent 6 }}
  {{- end }}
  {{- end }}
  {{- with .Values.config.puppet }}
  puppet:
    environmentTimeout: {{ .environmentTimeout }}
    storeconfigs: {{ .storeconfigs }}
    reports: {{ .reports }}
  {{- end }}
  {{- with .Values.config.code }}
  {{- if or .image .claimName }}
  code:
    {{- with .image }}
    image: {{ . }}
    {{- end }}
    {{- with .imagePullPolicy }}
    imagePullPolicy: {{ . }}
    {{- end }}
    {{- with .imagePullSecret }}
    imagePullSecret: {{ . }}
    {{- end }}
    {{- with .claimName }}
    claimName: {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
