{{- range $entry := .Values.servers }}
---
apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Server
metadata:
  name: {{ include "openvox-stack.serverName" (dict "root" $ "entry" $entry) }}
spec:
  configRef: {{ include "openvox-stack.configName" $ }}
  certificateRef: {{ include "openvox-stack.certName" (dict "root" $ "entry" $entry) }}
  {{- if hasKey $entry "ca" }}
  ca: {{ $entry.ca }}
  {{- end }}
  {{- if hasKey $entry "server" }}
  server: {{ $entry.server }}
  {{- end }}
  {{- if $entry.poolRefs }}
  poolRefs:
    {{- range $ref := $entry.poolRefs }}
    - {{ include "openvox-stack.poolName" (dict "root" $ "entry" (dict "name" $ref)) }}
    {{- end }}
  {{- end }}
  replicas: {{ $entry.replicas | default 1 }}
  {{- with $entry.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.javaArgs }}
  javaArgs: {{ . | quote }}
  {{- end }}
  {{- with $entry.maxActiveInstances }}
  maxActiveInstances: {{ . }}
  {{- end }}
  {{- with $entry.image }}
  image:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.code }}
  code:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.autoscaling }}
  autoscaling:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.pdb }}
  pdb:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.networkPolicy }}
  networkPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $entry.priorityClassName }}
  priorityClassName: {{ . }}
  {{- end }}
{{- end }}
