apiVersion: v2
name: openvox-operator
description: Kubernetes Operator for running OpenVox Server environments
type: application
version: 0.0.0
appVersion: "0.0.0"
home: https://github.com/slauger/openvox-operator
sources:
  - https://github.com/slauger/openvox-operator
maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
    url: https://lauger.de
keywords:
  - openvox
  - puppet
  - operator
  - kubernetes
