replicaCount: 1

image:
  repository: ghcr.io/slauger/openvox-operator
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

leaderElect: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
