apiVersion: rbac.authorization.k8s.io/v1
{{- if eq .Values.scope.mode "namespace" }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "openvox-operator.fullname" . }}
  {{- if eq .Values.scope.mode "namespace" }}
  namespace: {{ .Values.scope.watchNamespace | default .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "openvox-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if eq .Values.scope.mode "namespace" }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "openvox-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openvox-operator.serviceAccountName" . }}
    namespace: {{ if eq .Values.scope.mode "namespace" }}{{ .Values.scope.watchNamespace | default .Release.Namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}
