{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvox-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openvox-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "openvox-operator.selectorLabels" . | nindent 4 }}
{{- end }}
