---
apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Config
metadata:
  name: production
  namespace: openvox
spec:
  image:
    repository: ghcr.io/slauger/openvox-server
    tag: "8.12.1"
  puppetdb:
    serverUrls:
      - https://openvoxdb:8081
  puppet:
    environmentTimeout: unlimited
    storeconfigs: true
    storeBackend: puppetdb
    reports: puppetdb
