---
apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Pool
metadata:
  name: puppet
  namespace: openvox-system
spec:
  environmentRef: production
  selector:
    openvox.voxpupuli.org/role: server
  service:
    type: ClusterIP
    port: 8140
