---
apiVersion: openvox.voxpupuli.org/v1alpha1
kind: Server
metadata:
  name: production-server
  namespace: openvox-system
spec:
  environmentRef: production
  ca: true
  compiler: true
  replicas: 1
  javaArgs: "-Xms512m -Xmx1024m"
