//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenVoxServer) DeepCopyInto(out *OpenVoxServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenVoxServer.
func (in *OpenVoxServer) DeepCopy() *OpenVoxServer {
	if in == nil {
		return nil
	}
	out := new(OpenVoxServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenVoxServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenVoxServerList) DeepCopyInto(out *OpenVoxServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenVoxServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenVoxServerList.
func (in *OpenVoxServerList) DeepCopy() *OpenVoxServerList {
	if in == nil {
		return nil
	}
	out := new(OpenVoxServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenVoxServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenVoxServerSpec) DeepCopyInto(out *OpenVoxServerSpec) {
	*out = *in
	in.Image.DeepCopyInto(out)
	in.CA.DeepCopyInto(&out.CA)
	in.Compilers.DeepCopyInto(&out.Compilers)
	in.Puppet.DeepCopyInto(&out.Puppet)
	out.PuppetDB = in.PuppetDB
	in.Code.DeepCopyInto(&out.Code)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenVoxServerSpec.
func (in *OpenVoxServerSpec) DeepCopy() *OpenVoxServerSpec {
	if in == nil {
		return nil
	}
	out := new(OpenVoxServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CASpec) DeepCopyInto(out *CASpec) {
	*out = *in
	if in.DNSAltNames != nil {
		in, out := &in.DNSAltNames, &out.DNSAltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
	out.IntermediateCA = in.IntermediateCA
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CASpec.
func (in *CASpec) DeepCopy() *CASpec {
	if in == nil {
		return nil
	}
	out := new(CASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntermediateCASpec) DeepCopyInto(out *IntermediateCASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntermediateCASpec.
func (in *IntermediateCASpec) DeepCopy() *IntermediateCASpec {
	if in == nil {
		return nil
	}
	out := new(IntermediateCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompilerSpec) DeepCopyInto(out *CompilerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Autoscaling = in.Autoscaling
	if in.DNSAltNames != nil {
		in, out := &in.DNSAltNames, &out.DNSAltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompilerSpec.
func (in *CompilerSpec) DeepCopy() *CompilerSpec {
	if in == nil {
		return nil
	}
	out := new(CompilerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetSpec) DeepCopyInto(out *PuppetSpec) {
	*out = *in
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetSpec.
func (in *PuppetSpec) DeepCopy() *PuppetSpec {
	if in == nil {
		return nil
	}
	out := new(PuppetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PuppetDBSpec) DeepCopyInto(out *PuppetDBSpec) {
	*out = *in
	if in.ServerURLs != nil {
		in, out := &in.ServerURLs, &out.ServerURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PuppetDBSpec.
func (in *PuppetDBSpec) DeepCopy() *PuppetDBSpec {
	if in == nil {
		return nil
	}
	out := new(PuppetDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSpec) DeepCopyInto(out *CodeSpec) {
	*out = *in
	in.R10k.DeepCopyInto(&out.R10k)
	out.Volume = in.Volume
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSpec.
func (in *CodeSpec) DeepCopy() *CodeSpec {
	if in == nil {
		return nil
	}
	out := new(CodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *R10kSpec) DeepCopyInto(out *R10kSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new R10kSpec.
func (in *R10kSpec) DeepCopy() *R10kSpec {
	if in == nil {
		return nil
	}
	out := new(R10kSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeVolumeSpec) DeepCopyInto(out *CodeVolumeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeVolumeSpec.
func (in *CodeVolumeSpec) DeepCopy() *CodeVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(CodeVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenVoxServerStatus) DeepCopyInto(out *OpenVoxServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenVoxServerStatus.
func (in *OpenVoxServerStatus) DeepCopy() *OpenVoxServerStatus {
	if in == nil {
		return nil
	}
	out := new(OpenVoxServerStatus)
	in.DeepCopyInto(out)
	return out
}
