package main

import (
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"

	"github.com/slauger/openvox-operator/internal/puppet"
	"gopkg.in/yaml.v3"
)

// PolicyConfig is the YAML structure generated by the operator and read by this binary.
type PolicyConfig struct {
	Policies []Policy `yaml:"policies"`
}

// Policy defines a single signing policy.
type Policy struct {
	Name          string             `yaml:"name"`
	Any           bool               `yaml:"any,omitempty"`
	Pattern       *PatternConf       `yaml:"pattern,omitempty"`
	DNSAltNames   *PatternConf       `yaml:"dnsAltNames,omitempty"`
	CSRAttributes []CSRAttributeConf `yaml:"csrAttributes,omitempty"`
}

// PatternConf defines certname glob matching.
type PatternConf struct {
	Allow []string `yaml:"allow"`
}

// CSRAttributeConf defines a single CSR extension attribute to match.
type CSRAttributeConf struct {
	Name  string `yaml:"name"`
	Value string `yaml:"value"`
}

// loadPolicyConfig reads and parses the policy YAML file.
func loadPolicyConfig(path string) (*PolicyConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading policy config: %w", err)
	}
	var cfg PolicyConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing policy config: %w", err)
	}
	return &cfg, nil
}

// parseCSR decodes a PEM-encoded CSR from raw bytes.
func parseCSR(pemData []byte) (*x509.CertificateRequest, error) {
	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found in CSR")
	}
	return x509.ParseCertificateRequest(block.Bytes)
}

// extractCSRAttribute extracts a CSR extension value by attribute name.
func extractCSRAttribute(csr *x509.CertificateRequest, attrName string) (string, bool) {
	oid, ok := puppet.OIDByName(attrName)
	if !ok {
		return "", false
	}
	return extractCSRExtensionByOID(csr, oid)
}

// extractCSRExtensionByOID extracts a CSR extension value by OID.
func extractCSRExtensionByOID(csr *x509.CertificateRequest, oid asn1.ObjectIdentifier) (string, bool) {
	for _, ext := range csr.Extensions {
		if ext.Id.Equal(oid) {
			return decodeExtensionValue(ext), true
		}
	}
	return "", false
}

// decodeExtensionValue tries to decode an extension as a UTF8/printable string.
func decodeExtensionValue(ext pkix.Extension) string {
	var val string
	if _, err := asn1.Unmarshal(ext.Value, &val); err == nil {
		return val
	}
	// Fallback: return raw bytes as string
	return string(ext.Value)
}

// evaluatePolicies checks all policies (OR). Returns true if any policy matches.
func evaluatePolicies(cfg *PolicyConfig, certname string, csr *x509.CertificateRequest) bool {
	for _, policy := range cfg.Policies {
		if evaluatePolicy(policy, certname, csr) {
			return true
		}
	}
	return false
}

// evaluatePolicy checks a single policy (AND within). All set fields must match.
func evaluatePolicy(policy Policy, certname string, csr *x509.CertificateRequest) bool {
	// any: true approves unconditionally
	if policy.Any {
		return true
	}

	hasCondition := false

	if policy.Pattern != nil {
		hasCondition = true
		if !matchPattern(policy.Pattern, certname) {
			return false
		}
	}

	if len(policy.CSRAttributes) > 0 {
		hasCondition = true
		if !matchCSRAttributes(policy.CSRAttributes, csr) {
			return false
		}
	}

	// SAN validation: if CSR has SANs, they must be explicitly allowed
	if len(csr.DNSNames) > 0 {
		if policy.DNSAltNames == nil {
			return false
		}
		if !matchDNSAltNames(policy.DNSAltNames, csr.DNSNames) {
			return false
		}
	}

	// A policy with no conditions matches nothing
	return hasCondition
}

// matchPattern checks if certname matches any of the allow patterns.
func matchPattern(p *PatternConf, certname string) bool {
	for _, pattern := range p.Allow {
		if globMatch(pattern, certname) {
			return true
		}
	}
	return false
}

// matchCSRAttributes checks if all CSR attribute matchers match (AND logic).
func matchCSRAttributes(attrs []CSRAttributeConf, csr *x509.CertificateRequest) bool {
	for _, attr := range attrs {
		val, ok := extractCSRAttribute(csr, attr.Name)
		if !ok {
			return false
		}
		if val != attr.Value {
			return false
		}
	}
	return true
}

// matchDNSAltNames checks if all DNS SANs in the CSR match at least one allow pattern.
func matchDNSAltNames(p *PatternConf, dnsNames []string) bool {
	for _, san := range dnsNames {
		matched := false
		for _, pattern := range p.Allow {
			if globMatch(pattern, san) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

// globMatch implements simple glob matching with * and ? for Puppet certnames.
func globMatch(pattern, name string) bool {
	matched, err := filepath.Match(pattern, name)
	if err != nil {
		return false
	}
	return matched
}
