package main

import (
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// PolicyConfig is the YAML structure generated by the operator and read by this binary.
type PolicyConfig struct {
	Policies []Policy `yaml:"policies"`
}

// Policy defines a single signing policy.
type Policy struct {
	Name    string       `yaml:"name"`
	Any     bool         `yaml:"any,omitempty"`
	Pattern *PatternConf `yaml:"pattern,omitempty"`
	PSK     *PSKConf     `yaml:"psk,omitempty"`
	Token   *TokenConf   `yaml:"token,omitempty"`
}

// PatternConf defines certname glob matching.
type PatternConf struct {
	Allow []string `yaml:"allow"`
}

// PSKConf defines a pre-shared key rule.
type PSKConf struct {
	Value        string `yaml:"value"`
	CSRAttribute string `yaml:"csrAttribute"`
}

// TokenConf defines token-based authentication.
type TokenConf struct {
	Tokens       map[string]string `yaml:"tokens"`
	CSRAttribute string            `yaml:"csrAttribute"`
}

// Known Puppet CSR extension OIDs.
var puppetOIDs = map[string]asn1.ObjectIdentifier{
	"pp_uuid":             {1, 3, 6, 1, 4, 1, 34380, 1, 1, 1},
	"pp_instance_id":      {1, 3, 6, 1, 4, 1, 34380, 1, 1, 2},
	"pp_image_name":       {1, 3, 6, 1, 4, 1, 34380, 1, 1, 3},
	"pp_preshared_key":    {1, 3, 6, 1, 4, 1, 34380, 1, 1, 4},
	"pp_cost_center":      {1, 3, 6, 1, 4, 1, 34380, 1, 1, 5},
	"pp_product":          {1, 3, 6, 1, 4, 1, 34380, 1, 1, 6},
	"pp_project":          {1, 3, 6, 1, 4, 1, 34380, 1, 1, 7},
	"pp_application":      {1, 3, 6, 1, 4, 1, 34380, 1, 1, 8},
	"pp_service":          {1, 3, 6, 1, 4, 1, 34380, 1, 1, 9},
	"pp_employee":         {1, 3, 6, 1, 4, 1, 34380, 1, 1, 10},
	"pp_created_by":       {1, 3, 6, 1, 4, 1, 34380, 1, 1, 11},
	"pp_environment":      {1, 3, 6, 1, 4, 1, 34380, 1, 1, 12},
	"pp_role":             {1, 3, 6, 1, 4, 1, 34380, 1, 1, 13},
	"pp_software_version": {1, 3, 6, 1, 4, 1, 34380, 1, 1, 14},
	"pp_department":       {1, 3, 6, 1, 4, 1, 34380, 1, 1, 15},
	"pp_cluster":          {1, 3, 6, 1, 4, 1, 34380, 1, 1, 16},
	"pp_provisioner":      {1, 3, 6, 1, 4, 1, 34380, 1, 1, 17},
	"pp_region":           {1, 3, 6, 1, 4, 1, 34380, 1, 1, 18},
	"pp_datacenter":       {1, 3, 6, 1, 4, 1, 34380, 1, 1, 19},
	"pp_zone":             {1, 3, 6, 1, 4, 1, 34380, 1, 1, 20},
	"pp_network":          {1, 3, 6, 1, 4, 1, 34380, 1, 1, 21},
	"pp_securitypolicy":   {1, 3, 6, 1, 4, 1, 34380, 1, 1, 22},
	"pp_cloudplatform":    {1, 3, 6, 1, 4, 1, 34380, 1, 1, 23},
	"pp_apptier":          {1, 3, 6, 1, 4, 1, 34380, 1, 1, 24},
	"pp_hostname":         {1, 3, 6, 1, 4, 1, 34380, 1, 1, 25},
	"pp_owner":            {1, 3, 6, 1, 4, 1, 34380, 1, 1, 26},
	"pp_authorization":    {1, 3, 6, 1, 4, 1, 34380, 1, 3, 1},
	"pp_auth_token":       {1, 3, 6, 1, 4, 1, 34380, 1, 3, 2},
	"pp_cli_auth":         {1, 3, 6, 1, 4, 1, 34380, 1, 3, 39},
	"challengePassword":   {1, 2, 840, 113549, 1, 9, 7},
}

// loadPolicyConfig reads and parses the policy YAML file.
func loadPolicyConfig(path string) (*PolicyConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading policy config: %w", err)
	}
	var cfg PolicyConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing policy config: %w", err)
	}
	return &cfg, nil
}

// parseCSR decodes a PEM-encoded CSR from raw bytes.
func parseCSR(pemData []byte) (*x509.CertificateRequest, error) {
	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found in CSR")
	}
	return x509.ParseCertificateRequest(block.Bytes)
}

// extractCSRAttribute extracts a CSR extension value by attribute name.
func extractCSRAttribute(csr *x509.CertificateRequest, attrName string) (string, bool) {
	oid, ok := puppetOIDs[attrName]
	if !ok {
		return "", false
	}
	return extractCSRExtensionByOID(csr, oid)
}

// extractCSRExtensionByOID extracts a CSR extension value by OID.
func extractCSRExtensionByOID(csr *x509.CertificateRequest, oid asn1.ObjectIdentifier) (string, bool) {
	for _, ext := range csr.Extensions {
		if ext.Id.Equal(oid) {
			return decodeExtensionValue(ext), true
		}
	}
	return "", false
}

// decodeExtensionValue tries to decode an extension as a UTF8/printable string.
func decodeExtensionValue(ext pkix.Extension) string {
	var val string
	if _, err := asn1.Unmarshal(ext.Value, &val); err == nil {
		return val
	}
	// Fallback: return raw bytes as string
	return string(ext.Value)
}

// evaluatePolicies checks all policies (OR). Returns true if any policy matches.
func evaluatePolicies(cfg *PolicyConfig, certname string, csr *x509.CertificateRequest) bool {
	for _, policy := range cfg.Policies {
		if evaluatePolicy(policy, certname, csr) {
			return true
		}
	}
	return false
}

// evaluatePolicy checks a single policy (AND within). All set fields must match.
func evaluatePolicy(policy Policy, certname string, csr *x509.CertificateRequest) bool {
	// any: true approves unconditionally
	if policy.Any {
		return true
	}

	hasCondition := false

	if policy.Pattern != nil {
		hasCondition = true
		if !matchPattern(policy.Pattern, certname) {
			return false
		}
	}

	if policy.PSK != nil {
		hasCondition = true
		if !matchPSK(policy.PSK, csr) {
			return false
		}
	}

	if policy.Token != nil {
		hasCondition = true
		if !matchToken(policy.Token, certname, csr) {
			return false
		}
	}

	// A policy with no conditions matches nothing
	return hasCondition
}

// matchPattern checks if certname matches any of the allow patterns.
func matchPattern(p *PatternConf, certname string) bool {
	for _, pattern := range p.Allow {
		if globMatch(pattern, certname) {
			return true
		}
	}
	return false
}

// matchPSK checks if the CSR contains the expected PSK value.
func matchPSK(p *PSKConf, csr *x509.CertificateRequest) bool {
	val, ok := extractCSRAttribute(csr, p.CSRAttribute)
	if !ok {
		return false
	}
	return val == p.Value
}

// matchToken checks if the CSR contains a valid token for this certname.
func matchToken(t *TokenConf, certname string, csr *x509.CertificateRequest) bool {
	val, ok := extractCSRAttribute(csr, t.CSRAttribute)
	if !ok {
		return false
	}
	expected, exists := t.Tokens[certname]
	if !exists {
		return false
	}
	return val == expected
}

// globMatch implements simple glob matching with * and ? for Puppet certnames.
func globMatch(pattern, name string) bool {
	// Use filepath.Match which supports * and ? globs
	matched, err := filepath.Match(pattern, name)
	if err != nil {
		return false
	}
	return matched
}
