package main

import (
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/pem"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/slauger/openvox-operator/internal/puppet"
	"gopkg.in/yaml.v3"
)

// PolicyConfig is the YAML structure generated by the operator and read by this binary.
type PolicyConfig struct {
	Policies []Policy `yaml:"policies"`
}

// Policy defines a single signing policy.
type Policy struct {
	Name          string             `yaml:"name"`
	Any           bool               `yaml:"any,omitempty"`
	Certnames     *PatternConf       `yaml:"certnames,omitempty"`
	DNSAltNames   *PatternConf       `yaml:"dnsAltNames,omitempty"`
	IPAltNames    *PatternConf       `yaml:"ipAltNames,omitempty"`
	URIAltNames   *PatternConf       `yaml:"uriAltNames,omitempty"`
	EmailAltNames *PatternConf       `yaml:"emailAltNames,omitempty"`
	Extensions    *PatternConf       `yaml:"extensions,omitempty"`
	CSRAttributes []CSRAttributeConf `yaml:"csrAttributes,omitempty"`
}

// PatternConf defines certname glob matching.
type PatternConf struct {
	Allow []string `yaml:"allow"`
}

// CSRAttributeConf defines a single CSR extension attribute to match.
type CSRAttributeConf struct {
	Name  string `yaml:"name"`
	Value string `yaml:"value"`
}

// loadPolicyConfig reads and parses the policy YAML file.
func loadPolicyConfig(path string) (*PolicyConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading policy config: %w", err)
	}
	var cfg PolicyConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing policy config: %w", err)
	}
	return &cfg, nil
}

// parseCSR decodes a PEM-encoded CSR from raw bytes.
func parseCSR(pemData []byte) (*x509.CertificateRequest, error) {
	block, _ := pem.Decode(pemData)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found in CSR")
	}
	return x509.ParseCertificateRequest(block.Bytes)
}

// extractCSRAttribute extracts a CSR extension value by attribute name.
func extractCSRAttribute(csr *x509.CertificateRequest, attrName string) (string, bool) {
	oid, ok := puppet.OIDByName(attrName)
	if !ok {
		return "", false
	}
	return extractCSRExtensionByOID(csr, oid)
}

// extractCSRExtensionByOID extracts a CSR extension value by OID.
func extractCSRExtensionByOID(csr *x509.CertificateRequest, oid asn1.ObjectIdentifier) (string, bool) {
	for _, ext := range csr.Extensions {
		if ext.Id.Equal(oid) {
			return decodeExtensionValue(ext), true
		}
	}
	return "", false
}

// decodeExtensionValue tries to decode an extension as a UTF8/printable string.
func decodeExtensionValue(ext pkix.Extension) string {
	var val string
	if _, err := asn1.Unmarshal(ext.Value, &val); err == nil {
		return val
	}
	// Fallback: return raw bytes as string
	return string(ext.Value)
}

// evaluatePolicies checks all policies (OR). Returns true if any policy matches.
func evaluatePolicies(cfg *PolicyConfig, certname string, csr *x509.CertificateRequest) bool {
	for _, policy := range cfg.Policies {
		if evaluatePolicy(policy, certname, csr) {
			return true
		}
	}
	return false
}

// evaluatePolicy checks a single policy. The guard plane (privileged extensions
// and SAN types) is fail-closed and applies to every policy, including any:true,
// so no policy can implicitly waive escalation protection. The match plane
// (pattern, csrAttributes) is AND within a policy.
func evaluatePolicy(policy Policy, certname string, csr *x509.CertificateRequest) bool {
	// Guard plane: a CSR carrying a privileged authorization extension or a SAN
	// type the policy does not explicitly allow is never signed.
	if !guardExtensions(policy, csr) {
		return false
	}
	if !guardSANs(policy, csr) {
		return false
	}

	// any: true approves unconditionally once the guards pass.
	if policy.Any {
		return true
	}

	hasCondition := false

	if policy.Certnames != nil {
		hasCondition = true
		if !matchPattern(policy.Certnames, certname) {
			return false
		}
	}

	if len(policy.CSRAttributes) > 0 {
		hasCondition = true
		if !matchCSRAttributes(policy.CSRAttributes, csr) {
			return false
		}
	}

	// A policy with no conditions matches nothing.
	return hasCondition
}

// guardExtensions denies CSRs that carry a privileged authorization extension
// (OID under the 1.3.6.1.4.1.34380.1.3 arc) unless the policy explicitly allows
// it by name. Authorization-arc OIDs with no known name cannot be allow-listed
// and are always denied. Non-authorization extensions are not gated here.
func guardExtensions(policy Policy, csr *x509.CertificateRequest) bool {
	var allowed map[string]bool
	if policy.Extensions != nil {
		allowed = make(map[string]bool, len(policy.Extensions.Allow))
		for _, name := range policy.Extensions.Allow {
			allowed[name] = true
		}
	}
	for _, ext := range csr.Extensions {
		if !puppet.IsAuthorizationOID(ext.Id) {
			continue
		}
		name, known := puppet.NameByOID(ext.Id)
		if !known || !allowed[name] {
			return false
		}
	}
	return true
}

// guardSANs fail-closes every SAN type: if the CSR carries SANs of a given type,
// the policy must allow that type and every value must match an allow entry.
func guardSANs(policy Policy, csr *x509.CertificateRequest) bool {
	if len(csr.DNSNames) > 0 {
		if policy.DNSAltNames == nil || !matchDNSAltNames(policy.DNSAltNames, csr.DNSNames) {
			return false
		}
	}
	if len(csr.IPAddresses) > 0 {
		if policy.IPAltNames == nil || !allIPInCIDRs(policy.IPAltNames.Allow, csr.IPAddresses) {
			return false
		}
	}
	if len(csr.URIs) > 0 {
		if policy.URIAltNames == nil || !allWildcardMatch(policy.URIAltNames.Allow, uriStrings(csr.URIs)) {
			return false
		}
	}
	if len(csr.EmailAddresses) > 0 {
		if policy.EmailAltNames == nil || !allWildcardMatch(policy.EmailAltNames.Allow, csr.EmailAddresses) {
			return false
		}
	}
	return true
}

// allIPInCIDRs reports whether every IP is contained in at least one allowed
// CIDR range. Invalid CIDR entries never match (fail-closed on the allow side).
func allIPInCIDRs(cidrs []string, ips []net.IP) bool {
	nets := make([]*net.IPNet, 0, len(cidrs))
	for _, c := range cidrs {
		if _, n, err := net.ParseCIDR(c); err == nil {
			nets = append(nets, n)
		}
	}
	for _, ip := range ips {
		matched := false
		for _, n := range nets {
			if n.Contains(ip) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

// allWildcardMatch reports whether every name matches at least one wildcard
// pattern, where '*' spans any characters (including '/' and '@').
func allWildcardMatch(patterns, names []string) bool {
	for _, name := range names {
		matched := false
		for _, p := range patterns {
			if wildcardMatch(p, name) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

// wildcardMatch matches name against a pattern where '*' matches any sequence of
// characters; all other characters match literally. Unlike filepath.Match, '*'
// is not stopped by '/' or '@', which suits URIs and email addresses.
func wildcardMatch(pattern, name string) bool {
	parts := strings.Split(pattern, "*")
	if len(parts) == 1 {
		return pattern == name
	}
	if !strings.HasPrefix(name, parts[0]) {
		return false
	}
	name = name[len(parts[0]):]
	for _, seg := range parts[1 : len(parts)-1] {
		idx := strings.Index(name, seg)
		if idx < 0 {
			return false
		}
		name = name[idx+len(seg):]
	}
	return strings.HasSuffix(name, parts[len(parts)-1])
}

// uriStrings renders CSR URI SANs to their string form.
func uriStrings(uris []*url.URL) []string {
	out := make([]string, len(uris))
	for i, u := range uris {
		out[i] = u.String()
	}
	return out
}

// matchPattern checks if certname matches any of the allow patterns.
func matchPattern(p *PatternConf, certname string) bool {
	for _, pattern := range p.Allow {
		if globMatch(pattern, certname) {
			return true
		}
	}
	return false
}

// matchCSRAttributes checks if all CSR attribute matchers match (AND logic).
func matchCSRAttributes(attrs []CSRAttributeConf, csr *x509.CertificateRequest) bool {
	for _, attr := range attrs {
		val, ok := extractCSRAttribute(csr, attr.Name)
		if !ok {
			return false
		}
		if val != attr.Value {
			return false
		}
	}
	return true
}

// matchDNSAltNames checks if all DNS SANs in the CSR match at least one allow pattern.
func matchDNSAltNames(p *PatternConf, dnsNames []string) bool {
	for _, san := range dnsNames {
		matched := false
		for _, pattern := range p.Allow {
			if globMatch(pattern, san) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

// globMatch implements simple glob matching with * and ? for Puppet certnames.
func globMatch(pattern, name string) bool {
	matched, err := filepath.Match(pattern, name)
	if err != nil {
		return false
	}
	return matched
}
