signingPolicies:
  - name: autosign-any
    any: true

ca:
  external:
    url: https://e2e-ext-ca-a-ca-internal.e2e-ext-ca-a.svc:8140
    caSecretRef: external-ca-cert
    insecureSkipVerify: true

config:
  code:
    image: ghcr.io/slauger/openvox-e2e-code:latest
    imagePullPolicy: Always

servers:
  - name: ca
    ca: false
    server: true
    poolRefs: [server]
    certificate:
      certname: puppet
      dnsAltNames:
        - e2e-ext-ca-b-server
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi

pools:
  - name: server
    service:
      type: ClusterIP
      port: 8140
