signingPolicies:
  - name: autosign-any
    any: true

gateway:
  name: e2e-puppet-gateway

servers:
  - name: ca
    ca: true
    server: true
    poolRefs: [ca, server]
    certificate:
      certname: puppet
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi

pools:
  - name: ca
    service:
      type: ClusterIP
      port: 8140
  - name: server
    service:
      type: ClusterIP
      port: 8140
    route:
      enabled: true
      hostname: puppet.e2e.example.com
      injectDNSAltName: true
