FROM docker.io/library/golang:1.26 AS builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY api/ api/
COPY internal/ internal/
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -a -o manager ./cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7-1771346502

LABEL org.opencontainers.image.title="OpenVox Operator" \
      org.opencontainers.image.description="OpenVox Operator for Kubernetes/OpenShift" \
      org.opencontainers.image.vendor="slauger" \
      org.opencontainers.image.url="https://github.com/slauger/openvox-operator" \
      org.opencontainers.image.source="https://github.com/slauger/openvox-operator" \
      org.opencontainers.image.licenses="Apache-2.0"

COPY --from=builder /workspace/manager /manager

USER 1001:0

ENTRYPOINT ["/manager"]
