name: CI (Test Images)

on:
  push:
    branches: [main, develop]
    paths:
      - 'images/openvox-agent/**'
      - 'images/openvox-code/**'
      - 'images/openvox-mock/**'
      - 'cmd/mock/**'
  workflow_dispatch:

jobs:
  openvox-agent:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
    with:
      image_name: openvox-agent
      dockerfile: images/openvox-agent/Containerfile
      context: 'images/openvox-agent'
      sign: false

  openvox-code:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
    with:
      image_name: openvox-code
      dockerfile: images/openvox-code/Containerfile
      context: '.'
      sign: false

  openvox-mock:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
    with:
      image_name: openvox-mock
      dockerfile: images/openvox-mock/Containerfile
      context: '.'
      sign: false
