name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  unicode:
    uses: ./.github/workflows/_unicode-lint.yaml

  go:
    uses: ./.github/workflows/_go.yaml

  helm:
    uses: ./.github/workflows/_helm.yaml

  shellcheck:
    uses: ./.github/workflows/_shellcheck.yaml

  openvox-operator:
    needs: go
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: openvox-operator
      dockerfile: images/openvox-operator/Containerfile
      context: '.'

  openvox-server:
    needs: shellcheck
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: openvox-server
      dockerfile: images/openvox-server/Containerfile
      context: '.'

  openvox-db:
    needs: shellcheck
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: openvox-db
      dockerfile: images/openvox-db/Containerfile
      context: '.'

  openvox-code:
    needs: shellcheck
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: openvox-code
      dockerfile: images/openvox-code/Containerfile
      context: '.'
      sign: false

  openvox-agent:
    needs: shellcheck
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: openvox-agent
      dockerfile: images/openvox-agent/Containerfile
      context: 'images/openvox-agent'
      sign: false

  openvox-mock:
    needs: shellcheck
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: openvox-mock
      dockerfile: images/openvox-mock/Containerfile
      context: '.'
      sign: false
