name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unicode:
    uses: ./.github/workflows/_unicode-lint.yaml

  go:
    uses: ./.github/workflows/go.yaml

  helm:
    uses: ./.github/workflows/helm.yaml
    permissions:
      contents: read
      packages: write

  shellcheck:
    uses: ./.github/workflows/shellcheck.yaml

  openvox-operator:
    needs: go
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-operator
      dockerfile: images/openvox-operator/Containerfile
      context: '.'

  openvox-server:
    needs: shellcheck
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-server
      dockerfile: images/openvox-server/Containerfile
      context: '.'
