name: E2E

on:
  push:
    branches: [develop]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Custom image tag (default: short git SHA)'
        required: false
        type: string
        default: ''

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  openvox-operator:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-operator
      dockerfile: images/openvox-operator/Containerfile
      context: '.'
      push: true
      image_tag: ${{ inputs.image_tag }}

  openvox-server:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-server
      dockerfile: images/openvox-server/Containerfile
      context: '.'
      push: true
      image_tag: ${{ inputs.image_tag }}

  openvox-code:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-code
      dockerfile: images/openvox-code/Containerfile
      context: '.'
      push: true
      image_tag: ${{ inputs.image_tag }}
      sign: false

  openvox-agent:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-agent
      dockerfile: images/openvox-agent/Containerfile
      context: 'images/openvox-agent'
      push: true
      image_tag: ${{ inputs.image_tag }}
      sign: false

  openvox-db:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-db
      dockerfile: images/openvox-db/Containerfile
      context: '.'
      push: true
      image_tag: ${{ inputs.image_tag }}

  openvox-mock:
    uses: ./.github/workflows/_container-build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      image_name: openvox-mock
      dockerfile: images/openvox-mock/Containerfile
      context: '.'
      push: true
      image_tag: ${{ inputs.image_tag }}
      sign: false
